# Service Name
service: vws

provider:
  name: aws
  runtime: nodejs6.10
  stage: v1
  # profile: <PROFILE_NAME>
  environment:
    JCDECAUX_KEY: ${file(./config/secret.yml):JCDECAUX_KEY}
    VELIB_TABLE: ${self:resources.Resources.velibTable.Properties.TableName}
    VELIB_DETAILS_TABLE: ${self:resources.Resources.velibDetailsTable.Properties.TableName}
    GOBEE_DETAILS_TABLE: ${self:resources.Resources.gobeeDetailsTable.Properties.TableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource:
        - "Fn::Join": ["", ["arn:aws:dynamodb:", {"Ref": "AWS::Region"}, ":", {"Ref": "AWS::AccountId"}, ":table/velibTable*"]]
        - "Fn::Join": ["", ["arn:aws:dynamodb:", {"Ref": "AWS::Region"}, ":", {"Ref": "AWS::AccountId"}, ":table/velibDetailsTable*"]]
        - "Fn::Join": ["", ["arn:aws:dynamodb:", {"Ref": "AWS::Region"}, ":", {"Ref": "AWS::AccountId"}, ":table/gobeeDetailsTable*"]]

package:
  individually: true
  exclude:
    - test/**
    - .git/**

functions:
  velib:
    handler: src/velib/src/index.handler
    package:
      exclude: ./src/**
      include: ./src/velib/**
    events:
      - schedule:
          rate: cron(0 * * * ? *)
      - http:
          path: /velib
          method: GET
          cors: true
  velibStations:
    handler: src/velib/src/stations.handler
    package:
      exclude: ./src/**
      include: ./src/velib/**
    events:
      - schedule:
          rate: cron(0 * * * ? *)
      - http:
          path: /velib/stations
          method: GET
          cors: true
  gobeeParis:
    handler: src/velib/src/gobeeParis.handler
    package:
      exclude: ./src/**
      include: ./src/velib/**
    events:
      - schedule:
          rate: cron(0 * * * ? *)
      - http:
          path: /gobee/bikes/paris
          method: GET
          cors: true

resources:
  Resources:
    velibTable: # Store global statistics on all stations
      Type: AWS::DynamoDB::Table 
      Properties:
        TableName: velibTable
        AttributeDefinitions:
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: date
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
    velibDetailsTable: # Store statistics by stations
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: velibDetailsTable
        AttributeDefinitions:
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: date
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
    gobeeDetailsTable: # Store statistics by stations
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: gobeeDetailsTable
        AttributeDefinitions:
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: date
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2

custom:
  dynamodb:
    start:
      migrate: true

plugins:
  - serverless-mocha-plugin
  - serverless-dynamodb-local
  - serverless-offline